### ISSUE TITLE
Update README to direct users to googleapis/googleapis instead of googleapis/api-common-protos

### ISSUE THREAD

**Issue by parthea** [googleapis/api-common-protos#107]
The protos in the [googleapis/api-common-protos](https://github.com/googleapis/api-common-protos/tree/main/google) are not updated automatically and may be outdated. This issue tracks updating the [README](https://github.com/googleapis/api-common-protos/blob/main/README.md) to direct users to the [protos in googleapis/googleapis](https://github.com/googleapis/googleapis/tree/master/google/) instead which are updated regularly.

**Comment by take** [comment]
thanks for pointing this out! this helped me
