### ISSUE TITLE
Support for protobuf 5.X

### ISSUE THREAD

**Issue by RobPasMue** [googleapis/api-common-protos#134]
The Python package resulting from this repository and published on PyPI is not compatible with the new released versions of protobuf because it has an upper-limit on ``<5.0.0.dev0``.

**Comment by RobPasMue** [comment]
Transferring to https://github.com/googleapis/python-api-common-protos

**Comment by kojiromike** [comment]
Cross reference googleapis/python-api-common-protos#212
