### ISSUE TITLE
could you provide vcpkg

### ISSUE THREAD

**Issue by fgenolini** [googleapis/api-common-protos#2]
Hi,

Thanks for the C# Google.Api.CommonProtos NuGet package.
Could you also provide a vcpkg equivalent for C++?  There is already a vcpkg for  google-cloud-cpp, but this only includes the common protos as "third party" in vcpkg/buildtrees/google-cloud-cpp/src/v0.1.0-533022434b/third_party/googleapis/google/type/date.proto
With a dedicated vcpkg this would make the common protos available seamlessly to Visual Studio 2017 C++ projects from vcpkg/installed/x64-windows/include/google/type/date.proto
This is what the protobuf vcpkg provides (vcpkg/installed/x64-windows/include/google/protobuf/timestamp.proto)

Regards,

**Comment by lukesneeringer** [comment]
Hi @fgenolini,
I agree that a common protos package for C++ would be valuable. I personally do not have the expertise to do it, but we can look into it. :-)

**Comment by fgenolini** [comment]
thanks

**Comment by parthea** [comment]
I'm going to close this issue due to inactivity but please free free to re-open it with the current status.
