### ISSUE TITLE
Python package has 640 permissions instead of 644

### ISSUE THREAD

**Issue by dima-spire** [googleapis/api-common-protos#29]
If you unpack https://files.pythonhosted.org/packages/61/29/1549f61917eadd11650e42b78b4afcfe9cb467157af4510ab8cb59535f14/googleapis-common-protos-1.5.6.tar.gz, some files in `googleapis_common_protos.egg-info` directory have 640 permissions instead of 644.

I believe it should be 644.

Real-world impact is e.g. you cannot use it in AWS Lambda, as it's run from a different user, and will throw access denied exception on namespace_packages.txt file.

Similar to unrelated bug https://bugs.archlinux.org/task/30020

**Comment by lukesneeringer** [comment]
@dima-spire Thanks for reporting. We can fix this. :-)

**Comment by lukesneeringer** [comment]
This should be fixed in 1.5.7. Please reach out if not.

**Comment by lukesneeringer** [comment]
I just realized I should have set `o+x` on the directories, also. Doing that and releasing 1.5.8.
