### ISSUE TITLE
Include JS generated files in the npm package

### ISSUE THREAD

**Issue by clehene** [googleapis/api-common-protos#36]
Trying to solve 
```
Module not found: Error: Can't resolve './google/api/annotations_pb.js'
```

I've documented the use case here https://github.com/grpc-ecosystem/grpc-gateway/issues/834
Another related issue https://github.com/protocolbuffers/protobuf/issues/5318

**Comment by natiz** [comment]
@clehene were you able to solve this?

**Comment by clehene** [comment]
@natiz yes, but it's been 1.5 years and I can't remember the full context. I think the solution was to make the proto files available at compile-time (`-I`), essentially generating the js files with everything else. That said, I think nobody looks at this repo :/

**Comment by miraleung** [comment]
Closing as obsolete.
