### ISSUE TITLE
Deal with multiple resource_reference types over the same field

### ISSUE THREAD

**Issue by glerchundi** [googleapis/api-common-protos#47]
I was trying to define one parameter that could reference different types with no luck. The problem can be easily shown using IAM's GetRole method as an example:

```protobuf
// The request to get the definition of an existing role.
message GetRoleRequest {
  // The resource name of the role in one of the following formats:
  // `roles/{ROLE_NAME}`
  // `organizations/{ORGANIZATION_ID}/roles/{ROLE_NAME}`
  // `projects/{PROJECT_ID}/roles/{ROLE_NAME}`
  string name = 1;
}
```

In this case `google.api.resource_reference` cannot be used as only one type can be referenced.

I can think of two different ways to solve this:
* Make `resource_reference.type` a `repeated` field
* Use `oneof` in `name`

I think the first one would be the cleanest option but WDYT?

Any help would be much appreciated!

**Comment by glerchundi** [comment]
I just saw [this line](https://github.com/googleapis/api-common-protos/commit/4c0a203e3658ae0e56d47c817c2c5904116c0ae0#diff-9d7bd6aa3b028f30e4f63a1f176d2df3L108) in a commit of Apr which indeed makes a possible reference non repeatable. @lukesneeringer @eoogbe I guess this was made on purpose but how do you solve the use case [shown in there](https://github.com/googleapis/api-common-protos/commit/4c0a203e3658ae0e56d47c817c2c5904116c0ae0#diff-9d7bd6aa3b028f30e4f63a1f176d2df3L121) right now?

**Comment by lukesneeringer** [comment]
Closing this (see discussion in #48).
