### ISSUE TITLE
api/resource.proto: inconsistency between comments and definition

### ISSUE THREAD

**Issue by glerchundi** [googleapis/api-common-protos#53]
There are some examples inside the proto itself (`resource.proto`) which adds some references to a non-existent `name_descriptor` field.

Furthermore, the AIP establishes the use of a `type` & `pattern` properties to define the metadata associated to a specific resource. The comments make a plan to use those in a different way by wrapping it on a custom property (`name_descriptor`) and make it repeatable.

Is it possible to clarify this? Thanks!

@noahdietz @lukesneeringer as you were the ones involved in the MR.

**Comment by lukesneeringer** [comment]
Yes, we have a `name_descriptor` field internally whose fate is currently not clear. I need to work on this. Thanks for pointing it out!

**Comment by glerchundi** [comment]
@lukesneeringer one interesting benefit from the "new way" is that it's fairly easy to do automatic validation of all the resource name references over the entities/request.

That is to say, take this as an example:

```protobuf
message House {
 ...
}

message User {
    option (google.api.resource) = {
        type: "mycompanty.com/User"
        name_descriptor: {
            pattern: "houses/{house}/users/{user}"
            parent_type: "mycompanty.com/Home"
            parent_name_extractor: "houses/{house}"
        }
    }
    string name = 1 [(google.api.resource_reference) = {
        type: "mycompany.com/User"
    }];
    string parent = 2; [(google.api.resource_reference) = {
        type: "mycompany.com/User"
    }];
}
```

If I wanted to create an automatic generator for validating that all the resource references in a message belong to the same house (tenant) It's easy to extract the parent from the name value (as we already definied a parent extractor) and then do a cross comparison between all `resource_reference`s. Easy peasy.

This kind of things is what the new way allows to do.

Just putting my 2 cents.

**Comment by odsod** [comment]
We too are hand-rolling a fair amount of code that we could generate given the additional metadata from the `name_descriptor`. @lukesneeringer Could you share some context on why the fate is unclear? Is there a better approach using the current metadata that can be documented?

**Comment by odsod** [comment]
I think the parent type annotation would also be very useful when generating standard gRPC methods, requests and responses for a resource.

@lukesneeringer Poke :smile_cat:

**Comment by glerchundi** [comment]
Hi @lukesneeringer, did you have a better idea if that fate was worth it or not during these years? Thanks!

**Comment by hkdevandla** [comment]
@glerchundi ,  FYI: Luke is not owning this anymore.

About publicizing the name_descriptor field, that project is currently in the backlog and we may consider for as part of 2022 initiatives.

**Comment by glerchundi** [comment]
Thanks for the update @hkdevandla!

**Comment by parthea** [comment]
I'm going to close this issue as we're tracking the feature request internally in b/165605440. Please feel free to re-open this issue.

**Comment by glerchundi** [comment]
@parthea did you resolved that internal feature request somehow? Curious if this is still a need or not on your side, it continues to be on ours :D
