### ISSUE TITLE
field_behavior.proto (namely .pb.h) fails to build on Windows

### ISSUE THREAD

**Issue by nemo-cpt** [googleapis/api-common-protos#71]
Here OPTIONAL is used: https://github.com/googleapis/api-common-protos/blob/be41e82ef4af6406b4cf331af00a837f813c0c3b/google/api/field_behavior.proto#L41

But minwindef.h unconditionally defines OPTIONAL to nothing and so generated code fails to build.
The include comes via grpc/include/grpc/impl/codegen/port_platform.h which is included into generated code.

**Comment by miraleung** [comment]
This is widely used by many APIs as part of the [core `field_behavior`](https://github.com/googleapis/googleapis/blob/master/google/api/field_behavior.proto) proto. Thanks for the feedback.

**Comment by gasgallo** [comment]
@miraleung has this issue been addressed yet?
