### ISSUE TITLE
provide compiled common protos in swift

### ISSUE THREAD

**Issue by jagobagascon** [googleapis/api-common-protos#72]
We are currently working using different languages, using protos to generate some of the classes (some of them have dependencies on protos defined in this project). To ship our Swift project we have to generate and compile some protos under `google.rpc.*`, while on Java we just add them as a dependency.

It would be great if you could provide Swift packages with already compiled protos just like in other languages.

**Comment by parthea** [comment]
I'm going to close this issue due to inactivity but please feel free to re-open it.
