### ISSUE TITLE
api-common-protos version 1.7.0 with Protobuf 3.9.1 in Unity

### ISSUE THREAD

**Issue by Majid-AAI** [googleapis/api-common-protos#73]
After updating my google.Protobuf Library from 3.8.0 to 3.9.1 and GRPC Library from 1.22.0 to 2.25,0. 
I am facing this runtime crash :  "Could not load signature of Google.Type.CalendarPeriodReflection:get_Descriptor due to: Could not load file or assembly 'Google.Protobuf, Version=3.8.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604' or one of its dependencies. assembly:Google.Protobuf, Version=3.8.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604 type:<unknown type> member:(null) signature:<none>" 

Is there any missing class in google.Protobuf  3.9.1 or any compatibility issues.

![git issue ](https://user-images.githubusercontent.com/61189392/80570826-e853b380-8a14-11ea-85ff-4ea4728f6294.png)

**Comment by hkdevandla** [comment]
Have you tried with the most recent version of the protobuf 3.16.X or above as there are lot of updates that went into it?

**Comment by hkdevandla** [comment]
@Majid-AAI , closing this for now. Please let us know if you face issues after updating to the most recent version of the protobuf. Thanks!
