### ISSUE TITLE
out of sync with googleapis protos

### ISSUE THREAD

**Issue by arithmetic1728** [googleapis/api-common-protos#81]
The protos in `google/api` here are out of sync with https://github.com/googleapis/googleapis/tree/master/google/api

[python microgenerator](https://github.com/googleapis/gapic-generator-python) uses `google.api` python files from this repo, but generates code using protos from googleapis. The mismatch causes the generated unit tests fail to run.

**Comment by miraleung** [comment]
Closing as obsolete.
