### ISSUE TITLE
Identify the commit for a PyPI version

### ISSUE THREAD

**Issue by pingyeh** [googleapis/api-common-protos#96]
I'd like to import some of the `google.api` protos into my own proto, but I need to make sure I'm on the correct commit hash for the released PyPI package (e.g., [1.53.0](https://pypi.org/project/googleapis-common-protos/1.53.0/)) because my team depends on the PyPI package.

I searched the git log for `1.53.0` or some of the previous version numbers but found nothing.

Is there a way to identify the commits for released packages?

**Comment by parthea** [comment]
I'm going to close this issue as obsolete as it is recommended to use the [googleapis](https://github.com/googleapis/googleapis) repo instead.
